baseurl = "http://jhirniak.github.io/"
languageCode = "en-us"
title = "Jaroslaw Hirniak's Pirate Parrot"
theme = "hugo-steam-theme"
paginate = 40

[params]

	title = "Jaroslaw Hirniak's Blog"
	subtitle = "Fork, amplify, and release ideas."
	copyright = "Released under the MIT license."

	# You can choose between green, orange, red and blue.
	themeColor = "orange"
	# Enable Google Analytics be inserting your tracking code
	googleAnalytics = ""

	# To provide some metadata for search engines and the about section in the footer
	# feel free to add a few information about you and your website.
	name = "Jaroslaw Hirniak"
	bio = "... to be done"
	description = "Your description of the blog"
	location = "" # optional
	twitter = "ravanave" # optional
	github = "jhirniak" # optional

	# Enable a comment system
	# You can choose between Disqus or Google Plus by setting comments
	# to disqus or googleplus. For using Disqus you need to enter your
	# shortname in disqusShortname at the top of the configs. 
	comments = "googleplus"

	# Customize or translate the strings
	keepReadingStr = "Keep reading"
	backtotopStr = "Back to top"
	shareStr = "Share"
	pageNotFoundTitle = "404 - Page not found"
